#!/bin/bash

# Default username
USER="ubuntu"

# Extract the username if supplied
if [[ "$1" =~ @ ]]; then
  USER="${1%@*}"
  HOST="${1#*@}"
else
  HOST="$1"
fi

# Validate the hostname contains only valid characters (alphanumeric, dashes, and periods)
if ! [[ "$HOST" =~ ^[a-zA-Z0-9.-]+$ ]]; then
  echo "Hostname contains invalid characters."
  exit 1
fi

# Fetch the public IP using the PowerShell script
echo "Running pwsh -File $HOME/code/azbuilder/get-vm-ip.ps1 -HostName $HOST)"
IP=$(pwsh -File "$HOME/code/azbuilder/get-vm-ip.ps1" -HostName $HOST)
echo "IP received: $IP"

# Check if the IP is "NONE"
if [ "$IP" == "NONE" ]; then
  echo "No IP or an error occurred."
  exit 1
fi

# SSH into the server
ssh -A ${USER}@${IP}

