#!/usr/bin/env python3

import os
import argparse
import pyperclip
import sys
import fnmatch

def parse_gitignore(gitignore_path):
    ignore_patterns = []
    with open(gitignore_path, "r") as file:
        for line in file:
            stripped_line = line.strip()
            if stripped_line and not stripped_line.startswith("#"):
                ignore_patterns.append(stripped_line)
    return ignore_patterns

def is_ignored(path, ignore_patterns):
    for pattern in ignore_patterns:
        if fnmatch.fnmatch(path, pattern):
            return True
    return False

def read_file_contents(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return f.read()
    except UnicodeDecodeError:
        try:
            with open(file_path, "r", encoding="latin-1") as f:
                return f.read()
        except UnicodeDecodeError:
            print(f"Warning: Unable to decode file contents of {file_path}", file=sys.stderr)
            return None

def copy_python_files_to_clipboard(directory, recursive=False):
    buffer = ""
    ignore_patterns = []
    for root, dirs, files in os.walk(directory):
        if '.gitignore' in files:
            ignore_patterns.extend(parse_gitignore(os.path.join(root, '.gitignore')))

        for file in files:
            file_path = os.path.join(root, file)
            if file.endswith(".py") and not is_ignored(file_path, ignore_patterns):
                file_contents = read_file_contents(file_path)
                if file_contents is not None:
                    buffer += f"==== {file_path} ====\n"
                    buffer += file_contents + "\n\n"

        if not recursive:
            break

    pyperclip.copy(buffer)

def main():
    parser = argparse.ArgumentParser(description="Copy contents of Python files to clipboard")
    parser.add_argument("directory", help="Directory path to search for Python files")
    parser.add_argument("-r", "--recursive", action="store_true", help="Recursively search through directories")
    
    args = parser.parse_args()

    copy_python_files_to_clipboard(args.directory, args.recursive)

if __name__ == "__main__":
    main()

